#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2026, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: [
#     {
#     "timestamp": "2026-10-10T10:06:15",
#     "name": "@deepseek-ai/dsh",
#     "version": "0.2.0-rc.2",
#     "model": "deepseek-flash",
#     "contribution": {
#       "value": 10,
#       "units": "%"
#       }
#     }
#   ]
#
# Project properties for the build process.
#

openapi:
  schema:
    path: "v1.0"
    version: "1.0.8"

  python:
    version: "1.0.8.dev0"

  spring:
    version: "1.0.8-SNAPSHOT"

