#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2026, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: []
#
#

name: Calycopis test workflow

on:
  push:
    branches:
      - 'main'

  pull_request:

  workflow_dispatch:

jobs:

  build-java-spring:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      # https://github.com/actions/checkout
      - name: Checkout the schema project
        uses: actions/checkout@v7
        with:
          submodules: 'true'

      - name: Check the value of GITHUB_ENV.
        shell: bash
        run: |
          echo "${GITHUB_ENV}"

      - name: Check the contents of GITHUB_ENV.
        shell: bash
        run: |
          cat "${GITHUB_ENV}"

      - name: Check our environment variables
        shell: bash
        run: |
            echo "TEST_ENV [${TEST_ENV}]"
            echo "TEST_VAR [${TEST_VAR}]"
            echo "HARBOR_REGISTRY [${HARBOR_REGISTRY}]"
            echo "HARBOR_USERNAME [${HARBOR_USERNAME}]"
            echo "UKSRC_REPO_USERNAME [${UKSRC_REPO_USERNAME}]"
        env:
          TEST_ENV: ${{env.TEST_ENV}}
          TEST_VAR: ${{vars.TEST_VAR}}
          HARBOR_REGISTRY: ${{vars.HARBOR_REGISTRY}}
          HARBOR_USERNAME: ${{secrets.HARBOR_USERNAME}}
          UKSRC_REPO_USERNAME: ${{ secrets.UKSRC_REPO_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


